name: Traids Backend CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Send Slack - Deployment Started
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"attachments":[{"color":"#FFA500","text":":rocket: Deployment started for *traids-backend*"}]}' \
          ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Copy .env file
        run: cp /var/www/traids-envs/traids-env-be .env

      - name: Install dependencies
        run: npm install

      - name: Stop previous PM2 process
        run: pm2 stop traids-backend || true

      - name: Start application with PM2
        run: pm2 start npm --name "traids-backend" -- start

      - name: Send Slack - Deployment Success
        if: success()
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"attachments":[{"color":"#36A64F","text":":white_check_mark: Deployment successful for *traids-backend*"}]}' \
          ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Send Slack - Deployment Failure
        if: failure()
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"attachments":[{"color":"#FF0000","text":":x: Deployment failed for *traids-backend*"}]}' \
          ${{ secrets.SLACK_WEBHOOK_URL }}
